//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmacionLoQueSea
    {
        public int IdPedido { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string CodPostal { get; set; }
        public Nullable<int> Piso { get; set; }
        public string Departamento { get; set; }
        public Nullable<bool> EnvioPrioritario { get; set; }
        public string FechaRecepcion { get; set; }
        public string HoraRecepcion { get; set; }
        public Nullable<bool> PagoTarjeta { get; set; }
        public Nullable<decimal> AbonaEfectivo { get; set; }
        public string TitularTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string VencimientoTarjeta { get; set; }
        public string CodSeguridadTarjeta { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<bool> Anulado { get; set; }
    }
}
