//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliverEatEntities : DbContext
    {
        public DeliverEatEntities()
            : base("name=DeliverEatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfirmacionLoQueSea> ConfirmacionLoQueSea { get; set; }
        public virtual DbSet<ImagenPedidoLoQueSea> ImagenPedidoLoQueSea { get; set; }
        public virtual DbSet<PedidoLoQueSea> PedidoLoQueSea { get; set; }
    }
}
