//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoLoQueSea
    {
        public int IdPedido { get; set; }
        public string IdUsuario { get; set; }
        public string Descripcion { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string CodPostal { get; set; }
        public Nullable<int> Piso { get; set; }
        public string Departamento { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<bool> PedidoAbierto { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<bool> Anulado { get; set; }
    }
}
